### ISSUE TITLE
dark theme

### ISSUE THREAD

**Issue by mpictor** [sharpie7/circuitjs1#781]
It'd be nice to have a dark theme.

In the meantime, those with `stylus` installed can use the following. Far from perfect (doesn't fix menus, for one) but it is less bright :slightly_smiling_face:
```css
@-moz-document url-prefix("https://www.falstad.com/circuit/") {
body {
    background-color: #333;
}
body > hr {
    visibility: hidden;
}
div.gwt-MenuBar-horizontal {
    background-color: #343 !important;
    border-color: #555;
}
iframe {
    border-color: #454;
    width: 1500px;
    height: 900px;
}
body > div:nth-child(7) > div:nth-child(2) > div > div:nth-child(3) > table > tbody > tr > td > table > tbody > tr > td > canvas {
    filter: invert(.9)hue-rotate(180deg)brightness(.9);
}
.topButton {
    background-color: #561;
}
.topButton-red {
    background-color: #700;
    color: #7a7a7a;
}

.gwt-DialogBox{
    filter: invert(.9)hue-rotate(180deg)brightness(.9);
}

}
```
